---
name: default
kind: pipeline
type: docker

platform:
  os: linux
  arch: arm

trigger:
  event:
    - tag

steps:
- name: Set Tags
  image: debian:10
  commands:
    - apt-get update && apt-get install -y git
    - WORKER_TAG=$(git ls-remote --tags --refs https://github.com/our-story-media/ourstory-worker | grep -o 'refs/tags/v[0-9]*\.[0-9]*\.[0-9]*' | sort -r -V | head -n 1 | grep -o '[^\/]*$')
    - SERVER_TAG=$(git ls-remote --tags --refs https://github.com/our-story-media/ourstory-server | grep -o 'refs/tags/v[0-9]*\.[0-9]*\.[0-9]*' | sort -r -V | head -n 1 | grep -o '[^\/]*$')
    - echo -n "latest,$SERVER_TAG-$WORKER_TAG" > .tags
    - cat .tags
- name: Build and Push  
  image: plugins/docker
  settings:
    repo: bootlegger/titan-compact
    dockerfile: docker/titan/Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    build_args:
      - TARGETPLATFORM=linux/arm/v7
    context: docker/titan/
# - name: Upload
#   image: docker:dind
#   volumes:
#     - name: dockersock
#       path: /var/run/docker.sock
#   commands:
#     - apt-get update && apt-get install -y awscli
#     - docker/titan/uploadtitan-armv7.sh