---
name: default
kind: pipeline
type: docker

platform:
  os: linux
  arch: arm

trigger:
  event:
    - tag

steps:
- name: Build and Push  
  image: plugins/docker
  settings:
    repo: bootlegger/titan-compact
    dockerfile: docker/titan/Dockerfile
    auto_tag: true
    tags:
      - latest
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    build_args:
      - TARGETPLATFORM=linux/arm/v7
    context: docker/titan/
- name: Save and Upload
  image: docker
  commands:
    - docker pull bootlegger/titan-compact:latest
    - docker save -o ./indaba-update.tar bootlegger/titan-compact:latest
  - name: upload
  image: plugins/s3
  settings:
    bucket: ourstory-v2-live
    access_key: 
      from_secret: access_key
    secret_key: 
      from_secret: secret_key
    source: ./indaba-update.tar
    target: ./titan/indaba-update.tar
