---
name: default
kind: pipeline
type: docker

platform:
  os: linux
  arch: arm

trigger:
  event:
    - tag

steps:
- name: Build and Push  
  image: plugins/docker
  settings:
    repo: bootlegger/titan-compact
    dockerfile: docker/titan/Dockerfile
    auto_tag: true
    tags:
      - latest
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    build_args:
      - TARGETPLATFORM=linux/arm/v7
    context: docker/titan/