FROM nginx:alpine
LABEL maintainer="Tom Bartindale <tom.bartindale@monash.edu>"
RUN mkdir /templates
COPY docker/bootlegger.conf /etc/nginx/vhost.d/default
COPY docker/nginx.tmpl /templates/nginx.tmpl
COPY fallback/index.html /usr/share/nginx/html/index.html
COPY docker/server.conf /etc/nginx/conf.d/default.conf
VOLUME /templates