FROM node:10-buster

LABEL maintainer="Tom Bartindale <tom.bartindale@ncl.ac.uk>"

RUN mkdir -p /usr/src/app/upload
# && npm i -g grunt-cli nodemon --silent

WORKDIR /usr/src/app



RUN npm install -g nodemon

RUN wget https://fastdl.mongodb.org/tools/db/mongodb-database-tools-ubuntu1604-arm64-100.7.2.deb

RUN apt install -y ./mongodb-database-tools-ubuntu1604-arm64-100.7.2.deb

COPY package.json /usr/src/app/

COPY package-lock.json /usr/src/app/

RUN npm install 

RUN apt-get update && apt-get install -y rsync

COPY . /usr/src/app

EXPOSE 1337

VOLUME ["/usr/src/app/www","/usr/src/app/data","/usr/src/app/assets", "/usr/src/app/.tmp"]

CMD [ "npm", "start" ]
