FROM nginx:alpine
LABEL maintainer="Tom Bartindale <tom.bartindale@ncl.ac.uk>"
RUN mkdir /templates
COPY docker/bootlegger.conf /etc/nginx/vhost.d/default
COPY docker/nginx.tmpl /templates/nginx.tmpl
COPY fallback/index.html /usr/share/nginx/html/index.html
VOLUME /templates