FROM node:10

LABEL maintainer="Tom Bartindale <tom.bartindale@ncl.ac.uk>"

RUN mkdir -p /usr/src/app/upload
# && npm i -g grunt-cli nodemon --silent

WORKDIR /usr/src/app

RUN apt-get update && apt-get install -y git python gcc g++ make

# RUN npm install sharp

COPY package.json /usr/src/app/

RUN npm install

COPY . /usr/src/app

EXPOSE 1337

RUN npm install -g nodemon

RUN wget -qO - https://www.mongodb.org/static/pgp/server-4.2.asc | apt-key add - && echo "deb http://repo.mongodb.org/apt/debian stretch/mongodb-org/4.2 main" | tee /etc/apt/sources.list.d/mongodb-org-4.2.list && apt-get update && apt-get install -y mongodb-org-tools

# RUN grunt buildProd && mkdir -p /usr/src/app/upload/

RUN apt-get -y install rsync

VOLUME ["/usr/src/app/www","/usr/src/app/data","/usr/src/app/assets", "/usr/src/app/.tmp"]

CMD [ "npm", "start" ]
